defaults:
  - _self_
  - dataset: permuted_mnist
  - model: mlp
  - method: shield
  - exp: check_theorem_assumptions

fabric:
  _target_: lightning.Fabric
  num_nodes: 1
  devices: 1
  accelerator: cpu # or gpu

wandb:
  entity: ${oc.env:WANDB_ENTITY}
  project: ${oc.env:WANDB_PROJECT}