run_func:
    _target_: experiment.check_theorem_assumptions
seed: 1
log_dir: # set during runtime to automatically created dir
epsilon: 0.01
path_to_weights: saved_models/permuted_mnist/full_architecture_with_mixup_task_by_task/1